services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vulndb
      POSTGRES_USER: vulnuser
      POSTGRES_PASSWORD: vulnpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    command:
      - "start-dev"
      - "--import-realm"
      - "--hostname=http://host.docker.internal:8080"
      - "--hostname-strict=false"
      - "--http-enabled=true"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
#      - keycloak_data:/opt/keycloak/data
      - ./realm-full-export.json:/opt/keycloak/data/import/realm-full-export.json
    ports:
      - "8080:8080"

  app:
    build: ./app
    ports:
      - "8081:8081"
    depends_on:
      - db
      - keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata:
#  keycloak_data: