name: PR Title Check - Jira Ticket ID

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate title
        run: |
          TITLE="${{ github.event.pull_request.title }}"

          if [[ ! "$TITLE" =~ SCRUM-[0-9]+ ]]; then
            echo "PR title must contain Jira ticket ID."
            exit 1
          fi
